IF NOT EXISTS(
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'bronze_ref_vehicles'
)
BEGIN
    CREATE TABLE bronze_ref_vehicles(
        [Masse_OM_Max] INT,
        [Conso_vitesse_mixte_Max] FLOAT,
        [Essai_CO2_type_1] FLOAT,
        [Groupe] VARCHAR(50),
        [CO2_vitesse_mixte_Min] FLOAT,
        [Cylindrée] INT,
        [Conso_basse_vitesse_Max] FLOAT,
        [Bonus-Malus] VARCHAR(50),
        [Puissance_fiscale] INT,
        [Energie] VARCHAR(50),
        [CO2_basse_vitesse_Min] FLOAT,
        [Modèle] VARCHAR(50),
        [Libellé_modèle] VARCHAR(50),
        [Essai_HC] FLOAT,
        [Conso_vitesse_mixte_Min] FLOAT,
        [Type_de_boite] VARCHAR(50),
        [CO2_vitesse_mixte_Max] FLOAT,
        [Puissance_maximale] INT,
        [CO2_moyenne_vitesse_Min] FLOAT,
        [Carrosserie] VARCHAR(50),
        [CO2_basse_vitesse_Max] FLOAT,
        [Gamme] VARCHAR(50),
        [CO2_T-haute_vitesse_Min] FLOAT,
        [Nombre_rapports] INT,
        [Barème_Bonus-Malus] INT,
        [Essai_particules] FLOAT,
        [Conso_haute_vitesse_Max] FLOAT,
        [_i] INT PRIMARY KEY,
        [Description_Commerciale] VARCHAR(200),
        [Conso_T-haute_vitesse_Max] FLOAT,
        [CO2_haute_vitesse_Max] FLOAT,
        [CO2_T-haute_vitesse_Max] FLOAT,
        [CO2_moyenne_vitesse_Max] FLOAT,
        [Masse_OM_Min] INT,
        [Conso_moyenne_vitesse_Max] FLOAT,
        [Conso_basse_vitesse_Min] FLOAT,
        [Marque] VARCHAR(50),
        [Rapport_poids-puissance] FLOAT,
        [_rand] INT,
        [Poids_à_vide] INT,
        [Conso_moyenne_vitesse_Min] FLOAT,
        [Conso_haute_vitesse_Min] FLOAT,
        [Essai_Nox] FLOAT,
        [Conso_T-haute_vitesse_Min] FLOAT,
        [CO2_haute_vitesse_Min] FLOAT,
        [Prix_véhicule] INT,
        [_score] INT,
        [_id] VARCHAR(100),
        [Puissance_nominale_électrique] FLOAT,
        [Autonomie_elec_Max] FLOAT,
        [Autonomie_elec_urbain_Max] FLOAT,
        [Conso_elec_Max] FLOAT,
        [Essai_HCNox] FLOAT,
        [Conso_elec_Min] FLOAT,
        [Autonomie_elec_urbain_Min] FLOAT,
        [Autonomie_elec_Min] FLOAT
    )
END
;
